# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(894, 670)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sQlogo = QtWidgets.QLabel(self.centralwidget)
        self.sQlogo.setGeometry(QtCore.QRect(170, 30, 541, 111))
        self.sQlogo.setAutoFillBackground(True)
        self.sQlogo.setText("")
        self.sQlogo.setPixmap(QtGui.QPixmap("D:/ASASASAS.png"))
        self.sQlogo.setScaledContents(False)
        self.sQlogo.setObjectName("sQlogo")
        self.openFile = QtWidgets.QPushButton(self.centralwidget)
        self.openFile.setGeometry(QtCore.QRect(140, 370, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.openFile.setFont(font)
        self.openFile.setObjectName("openFile")
        self.filePath = QtWidgets.QLabel(self.centralwidget)
        self.filePath.setGeometry(QtCore.QRect(140, 240, 601, 16))
        self.filePath.setObjectName("filePath")
        self.runFile = QtWidgets.QPushButton(self.centralwidget)
        self.runFile.setGeometry(QtCore.QRect(580, 370, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.runFile.setFont(font)
        self.runFile.setObjectName("runFile")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 894, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.openFile.setStatusTip(_translate("MainWindow", "Click this and it will redirect you to your local file explorer."))
        self.openFile.setText(_translate("MainWindow", "Open Folder"))
        self.filePath.setText(_translate("MainWindow", "TextLabel"))
        self.runFile.setStatusTip(_translate("MainWindow", "Click this and it will start to run."))
        self.runFile.setText(_translate("MainWindow", "Run Bot"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
